#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t ProjectLlama"

$L "Welcome to ProjectLlama! You're running Android `getprop ro.build.version.release` with ProjectLlama version `getprop ro.llama.version`";
